// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetDotNet.DbContexts;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.DossiersMedicaux", b =>
                {
                    b.Property<int>("DossierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DossierId"));

                    b.Property<DateTime?>("ConsultationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocteur")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Prescriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatsExamens")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DossierId");

                    b.HasIndex("IdDocteur");

                    b.HasIndex("PatientID");

                    b.ToTable("DossiersMedicaux");
                });

            modelBuilder.Entity("WebApplication3.Models.RendezVous", b =>
                {
                    b.Property<int>("RendezVousId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RendezVousId"));

                    b.Property<string>("ConsultationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocteur")
                        .HasColumnType("int");

                    b.Property<int>("IdPatients")
                        .HasColumnType("int");

                    b.HasKey("RendezVousId");

                    b.HasIndex("IdDocteur");

                    b.HasIndex("IdPatients");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("WebApplication3.Models.Users", b =>
                {
                    b.Property<int>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsers"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsers");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Users");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApplication3.Models.Docteurs", b =>
                {
                    b.HasBaseType("WebApplication3.Models.Users");

                    b.HasDiscriminator().HasValue("Docteurs");
                });

            modelBuilder.Entity("WebApplication3.Models.Patients", b =>
                {
                    b.HasBaseType("WebApplication3.Models.Users");

                    b.HasDiscriminator().HasValue("Patients");
                });

            modelBuilder.Entity("WebApplication3.Models.DossiersMedicaux", b =>
                {
                    b.HasOne("WebApplication3.Models.Users", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDocteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Users", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication3.Models.RendezVous", b =>
                {
                    b.HasOne("WebApplication3.Models.Users", "Doctor")
                        .WithMany()
                        .HasForeignKey("IdDocteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Users", "Patient")
                        .WithMany()
                        .HasForeignKey("IdPatients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
